# Generated by Django 3.2.5 on 2021-07-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, verbose_name='호스트명')),
                ('email', models.CharField(max_length=30, verbose_name='이메일')),
                ('contact', models.CharField(max_length=20, verbose_name='대표 전화')),
                ('phone', models.CharField(max_length=20, verbose_name='휴대폰')),
            ],
            options={
                'verbose_name': '호스트',
                'verbose_name_plural': '호스트',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='시')),
                ('district', models.CharField(max_length=10, null=True, verbose_name='군/구')),
                ('name', models.CharField(max_length=20, verbose_name='지역명')),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('name', models.CharField(max_length=128, verbose_name='공간명')),
                ('summary', models.TextField(blank=True, max_length=30, null=True, verbose_name='한 줄 소개')),
                ('description', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('hashtag', models.CharField(blank=True, max_length=128, null=True, verbose_name='태그')),
                ('main_image', models.CharField(max_length=255, verbose_name='대표 이미지')),
                ('open_time', models.CharField(max_length=4, verbose_name='운영 시작 시간 (ex: 0900)')),
                ('close_time', models.CharField(max_length=4, verbose_name='운영 마감 시간 (ex: 2400)')),
                ('off_days', models.CharField(max_length=20, null=True, verbose_name='정기휴무 (월 0 일 6 ex: [0, 1, 6]')),
                ('max_fit', models.IntegerField(verbose_name='최대 인원')),
                ('activate', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '공간',
                'verbose_name_plural': '공간',
            },
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='공간 분류')),
                ('description', models.CharField(max_length=100, verbose_name='유형 소개')),
            ],
            options={
                'verbose_name': '공간 유형',
                'verbose_name_plural': '공간 유형',
            },
        ),
        migrations.CreateModel(
            name='SpacePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='패키지명')),
                ('price', models.IntegerField(verbose_name='패키지 가격')),
                ('check_in', models.CharField(max_length=4, verbose_name='체크인 (ex: 1800)')),
                ('check_out', models.CharField(max_length=4, verbose_name='체크아웃 (ex: 0700)')),
                ('check_out_next_day', models.BooleanField(verbose_name='익일 체크아웃 여부')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space')),
            ],
            options={
                'verbose_name': '패키지',
                'verbose_name_plural': '패키지',
            },
        ),
        migrations.CreateModel(
            name='SpacePackageSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='행사가 적용 시작일')),
                ('end_date', models.DateField(verbose_name='행사가 적용 종료일')),
                ('special_price', models.IntegerField(verbose_name='행사가')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.spacepackage')),
            ],
            options={
                'verbose_name': '패키지 행사가',
                'verbose_name_plural': '패키지 행사가',
            },
        ),
        migrations.AddField(
            model_name='space',
            name='categories',
            field=models.ManyToManyField(to='space.SpaceCategory', verbose_name='공간 유형'),
        ),
        migrations.AddField(
            model_name='space',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.host', verbose_name='호스트'),
        ),
        migrations.AddField(
            model_name='space',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.location', verbose_name='위치'),
        ),
    ]
